### ISSUE TITLE
track usage by website?

### ISSUE THREAD

**Issue by syphar** [green-coding-berlin/hog#15] opened 2023-10-19 05:53 UTC
I'm not sure if this even possible, but it definitely would be interesting (IMO): 

The same way I want to know which processes that are run by my terminal use the energy, I would love to know **which websites use the most energy in my browser**.

**Comment by ribalba** [comment] 2023-10-19 08:20
Hey, I have been thinking about the same thing. The problem is that the browsers keep the data quite hidden. Firefox has a really good project with https://firefox-source-docs.mozilla.org/performance/power_profiling_overview.html which gives you a great insight but only if you enable it and it isn't really thought to run all the time. Other engines don't really expose the level of detail we need. Chrome for example only shows %CPU which isn't really that useful https://www.green-coding.berlin/case-studies/cpu-utilization-usefulness/ 
But I would love to see energy data in a view like this.
<img width="597" alt="Screenshot 2023-10-19 at 10 18 43" src="https://github.com/green-coding-berlin/hog/assets/39629/a7a98c67-bbad-417d-a20a-dc9706ef773f">

Closing for now as it is out of scope but will start thinking about how to implement this in a simple fashion.

**Closed by ribalba** 2023-10-19 08:20 UTC
